use_frameworks!

platform :ios, '9.0'

target 'NexusRefresh_Example' do
  pod 'NexusRefresh', :path => '../'
  pod 'SnapKit'

  target 'NexusRefresh_Tests' do
    inherit! :search_paths

    
  end
end
